#!/bin/sh
echo "Checking commit message: $(cat $1)" >&2
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    echo "Commit message format check failed" >&2
    exit 1
fi

if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "Length check failed" >&2
    exit 1
fi